/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MichalHomenda
 */
public class Comparacion_de_dos_numeros extends javax.swing.JFrame {

    /**
     * Creates new form Comparacion_de_dos_numeros
     */
    public Comparacion_de_dos_numeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNum1 = new javax.swing.JLabel();
        jLNum2 = new javax.swing.JLabel();
        jTFNum1 = new javax.swing.JTextField();
        jTFNum2 = new javax.swing.JTextField();
        jBtnComparar = new javax.swing.JButton();
        jLRes = new javax.swing.JLabel();
        jLComp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comparacion de dos numeros");

        jLNum1.setText("Introduzca el primer número");

        jLNum2.setText("Introduzca el segundo número");

        jTFNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNum1ActionPerformed(evt);
            }
        });

        jBtnComparar.setText("Comparar");
        jBtnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCompararActionPerformed(evt);
            }
        });

        jLComp.setText("Resultado comparacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNum1)
                            .addComponent(jLNum2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 557, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNum1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jTFNum2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnComparar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLComp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNum1)
                    .addComponent(jTFNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNum2)
                    .addComponent(jTFNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jBtnComparar)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLComp))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNum1ActionPerformed

    private void jBtnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCompararActionPerformed
        // TODO add your handling code here:
        
        String num1 = jTFNum1.getText();
        String num2 = jTFNum2.getText();
        
        String newNum1 = num1.replace(",", ".");
        String newNum2 = num2.replace(",", ".");
        
        Double number1 = Double.parseDouble(num1);
        Double number2 = Double.parseDouble(num2);
        
        compararNumeros(number1, number2);
       
        
    }//GEN-LAST:event_jBtnCompararActionPerformed

    public void compararNumeros(double num1 ,double num2){
        
        
        if(num1 > num2){
            jLRes.setText( "Numero 1 es " + num1 + " y el Numero 2 es "
                    + num2 + ". Por tanto el numero 1 (" + num1
                    + ") es mayor que el número 2 (" + num2 +")");
        } else if (num1 < num2) {
            jLRes.setText( "Numero 1 es " + num1 + " y el Numero 2 es "
                    + num2 + ". Por tanto el numero 1 (" + num1 + ") es menor que el número 2 (" + num2 +")");
        } else {
            jLRes.setText( "Numero 1 es " + num1 + " y el Numero 2 es "
                    + num2 + ". Por tanto el numero 1 (" + num1 + ") es igual al número 2 (" + num2 +")");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comparacion_de_dos_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comparacion_de_dos_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comparacion_de_dos_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comparacion_de_dos_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comparacion_de_dos_numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnComparar;
    private javax.swing.JLabel jLComp;
    private javax.swing.JLabel jLNum1;
    private javax.swing.JLabel jLNum2;
    private javax.swing.JLabel jLRes;
    private javax.swing.JTextField jTFNum1;
    private javax.swing.JTextField jTFNum2;
    // End of variables declaration//GEN-END:variables
}
